version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: sentinel-postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - sentinel-network

  minio:
    image: minio/minio
    container_name: sentinel-minio

    restart: unless-stopped

    env_file:
      - .env

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    command: server /data --console-address ":9001"

    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"

    volumes:
      - minio_data:/data

    networks:
      - sentinel-network

volumes:

  postgres_data:

  minio_data:

networks:

  sentinel-network:
    driver: bridge
